server {
    listen 8080;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;

    # Enviar variables de entorno de Docker a PHP-FPM
    # PHP-FPM por defecto limpia las variables de entorno, necesitamos decirle a Nginx que las pase.
    # Alternativamente configuramos fpm en clear_env = no, pero pasarlas asi tambien funciona.
    # En PHP-FPM se pueden usar las de $_ENV o getenv()
    
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php_backend:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
